apiVersion: v1
kind: Service
metadata:
  name: whoop-classifier-service
spec:
  type: LoadBalancer
  selector:
    app: whoop-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
